Bugfix min_ess
maxisi/ringdown pull request #27
Opened 2023-03-03 02:07 UTC by HarrisonS-Phys

Bug fix for min_ess runs, the recursion of fit.run() currently seems to be broken following the latest changes that were made to run() and models to allow for new sampling of priors

2023-03-03 04:01 UTC, maxisi commented
@HarrisonS-Phys please resolve conflicts with main branch before this can be merged

2023-03-03 20:45 UTC, HarrisonS-Phys commented
Should be fixed

2023-03-06 17:39 UTC, HarrisonS-Phys commented
@maxisi  you mentioned in person that there were some changes you'd like to see before merging, are there comments for those changes available on github?

2023-03-06 17:58 UTC, maxisi commented
@HarrisonS-Phys yes, do you see those right above your last comment?

2023-03-08 16:33 UTC, maxisi requested changes
@HarrisonS-Phys please see these review comments

2023-03-08 21:32 UTC, HarrisonS-Phys commented on ringdown/fit.py
> +            minimum effective sample size exceeds `min_ess` (def. `-0.1`).
I kept the default as None, and now set min_ess to be zero if None is passed.

2023-03-08 21:32 UTC, HarrisonS-Phys commented
I think all the changes from your review have been applied.

2023-03-09 16:47 UTC, merged